--- 
title: "Paving my path (Letters from 2019-2020)"
author: "Carlos Alcala a.k.a. Carlito Fluito"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["bibliography.bib"]
biblio-style: "apalike"
link-citations: yes
github-repo: carlitofluito/letters2019_20
description: "This is a compendium of some of the letters written, sent and received between September 2019 and September 2020."
---

# Preamble {-#preamble}

We are socially fragmented. 

Memory, knowledge, lives, even identities. Everything is dispersed (another argument supporting the non-local consciousness theory). 

The aim of this epistolary work is to know a bit better what I am now thorugh the compilation of pieces of what I have been. I have been told in the past that there was wisdom in the texts I wrote, and I am sure that there is wisdom in the texts I received. 
I hope you find something that makes your life more meaningful and satisfactory. I hope you find a bunch of human beings that, like you, have suffered and have enjoyed moments of their lives. A bunch of human beings that, after all, have lived.

## A bit of context {-#context}

In September 2019, I started my second year as a Ph.D. student at UCLOuvain, in Belgium. A bit later, I would get involved in a deep and turbulent relationship that made me see life differently. Later on, I change my life path, stop the Ph.D. studies, and dedicate my time and life to become a spiritual psychologist, and a full-time artist. Then, COVID-19 cought me in Berlin...
